const express = require('express')
const router = express.Router()
const authRoutes = require('./authRoutes')
const companyRoutes = require('./companyRoutes')
const productRoutes = require('./productRoutes')
const orderRoutes = require('./orderRoutes')
const paymentRoutes = require('./paymentRoutes')
const cartRoutes = require('./cartRoutes')
const cardRoutes = require('./bankAccountRoutes')
const categoryRoutes = require('./categoryRoutes')
const shortListRoutes = require('./shortListRoutes')
const listRoutes = require('./listRoutes')
const invoiceRoutes = require('./invoiceRoutes')
const fileRoutes = require('./fileRoutes')
const chatRoutes = require('./chatRoutes')
const aiRoutes = require('./aiRoutes')
const userRoutes = require('./userRoutes')
const versionRoutes = require('./versionRoutes')

// Signup route
router.use('/auth', authRoutes)
router.use('/company', companyRoutes)
router.use('/product', productRoutes)
router.use('/order', orderRoutes)
router.use('/payment', paymentRoutes)
router.use('/cart', cartRoutes)
router.use('/card', cardRoutes)
router.use('/category', categoryRoutes)
router.use('/shortList', shortListRoutes)
router.use('/list', listRoutes)
router.use('/invoice', invoiceRoutes)
router.use('/file', fileRoutes)
router.use('/chat', chatRoutes)
router.use('/ai', aiRoutes)
router.use('/user', userRoutes)
router.use('/version', versionRoutes)

module.exports = router
