const path = require("path");
const fs = require("fs").promises;
const { ShopProduct, ProductFile, Shop } = require("../models");
const { uploadDiskFileToS3, deleteFileFromS3 } = require("../utilities/s3Utils");

const EXT_TO_FILE_TYPE = {
  ".jpg":  "image",
  ".jpeg": "image",
  ".png":  "image",
  ".webp": "image",
  ".gif":  "image",
  ".bmp":  "image",
  ".tiff": "image",
  ".mp4":  "video",
  ".mpeg": "video",
  ".mov":  "video",
  ".avi":  "video",
  ".mkv":  "video",
  ".webm": "video",
  ".pdf":  "pdf",
  ".doc":  "doc",
  ".docx": "docx",
  ".ppt":  "ppt",
  ".pptx": "pptx",
  ".xls":  "xls",
  ".xlsx": "xlsx",
  ".txt":  "txt",
};

// Only image and video get thumbnails generated by s3Utils
const S3_FILE_TYPE = { image: "image", video: "video" };

class ProductFileService {
  async assertProductExists(productId) {
    const product = await ShopProduct.findByPk(productId);
    if (!product) {
      const err = new Error("Product not found.");
      err.statusCode = 404;
      throw err;
    }
    return product;
  }

  async assertOwner(product, userId) {
    const shop = await Shop.findByPk(product.shopId);
    if (!shop || shop.userId !== userId) {
      const err = new Error("Forbidden. Only the shop owner can manage product media.");
      err.statusCode = 403;
      throw err;
    }
  }

  async uploadMedia(productId, userId, files) {
    const product = await this.assertProductExists(productId);
    await this.assertOwner(product, userId);

    const records = await Promise.all(
      files.map(async (file, index) => {
        const ext = path.extname(file.originalname).toLowerCase();
        const file_type = EXT_TO_FILE_TYPE[ext] || "other";
        const s3FileType = S3_FILE_TYPE[file_type] ?? null;

        let file_url, s3_key, thumbnail_url;
        try {
          const result = await uploadDiskFileToS3(
            file.path,
            file.originalname,
            file.mimetype,
            s3FileType
          );
          file_url = result.url;
          s3_key = result.key;
          thumbnail_url = result.thumbnailUrl ?? null;
        } finally {
          await fs.unlink(file.path).catch(() => {});
        }

        return {
          shopProductId: productId,
          file_url,
          thumbnail_url,
          s3_key,
          file_name: file.originalname,
          file_type,
          sort_order: index,
        };
      })
    );

    return ProductFile.bulkCreate(records);
  }

  // Uploads picture files (product gallery, variation gallery) and generates a
  // thumbnail for each — the same S3 pipeline the media upload above uses.
  // Returns [{url, thumbnailUrl}] ready to persist.
  async uploadImages(files = []) {
    return Promise.all(
      files.map(async (file) => {
        try {
          const result = await uploadDiskFileToS3(
            file.path,
            file.originalname,
            file.mimetype,
            "image"
          );
          return { url: result.url, thumbnailUrl: result.thumbnailUrl ?? null };
        } finally {
          await fs.unlink(file.path).catch(() => {});
        }
      })
    );
  }

  async deleteFile(fileId, userId) {
    const file = await ProductFile.findByPk(fileId);
    if (!file) {
      const err = new Error("File not found.");
      err.statusCode = 404;
      throw err;
    }

    const product = await this.assertProductExists(file.shopProductId);
    await this.assertOwner(product, userId);

    // Delete from S3 Spaces first — if this fails, we do NOT delete the DB record
    // so the file remains tracked and can be retried
    if (file.s3_key) {
      await deleteFileFromS3(file.s3_key);
    }

    await file.destroy();
  }
}

module.exports = ProductFileService;
