const path = require("path");
const fs = require("fs").promises;
const { Service, ServiceFile } = require("../models");
const { uploadDiskFileToS3, deleteFileFromS3 } = require("../utilities/s3Utils");

const EXT_TO_FILE_TYPE = {
  ".jpg":  "image",
  ".jpeg": "image",
  ".png":  "image",
  ".webp": "image",
  ".gif":  "image",
  ".bmp":  "image",
  ".tiff": "image",
  ".mp4":  "video",
  ".mpeg": "video",
  ".mov":  "video",
  ".avi":  "video",
  ".mkv":  "video",
  ".webm": "video",
  ".pdf":  "pdf",
  ".doc":  "doc",
  ".docx": "docx",
  ".ppt":  "ppt",
  ".pptx": "pptx",
  ".xls":  "xls",
  ".xlsx": "xlsx",
  ".txt":  "txt",
};

// Only image and video get thumbnails generated by s3Utils
const S3_FILE_TYPE = { image: "image", video: "video" };

class ServiceFileService {
  async assertServiceExists(serviceId) {
    const service = await Service.findByPk(serviceId);
    if (!service) {
      const err = new Error("Service not found.");
      err.statusCode = 404;
      throw err;
    }
    return service;
  }

  async uploadMedia(serviceId, files) {
    await this.assertServiceExists(serviceId);

    const records = await Promise.all(
      files.map(async (file, index) => {
        const ext = path.extname(file.originalname).toLowerCase();
        const file_type = EXT_TO_FILE_TYPE[ext] || "other";
        const s3FileType = S3_FILE_TYPE[file_type] ?? null;

        let file_url, s3_key;
        try {
          const result = await uploadDiskFileToS3(
            file.path,
            file.originalname,
            file.mimetype,
            s3FileType
          );
          file_url = result.url;
          s3_key = result.key;
        } finally {
          await fs.unlink(file.path).catch(() => {});
        }

        return {
          service_id: serviceId,
          file_url,
          s3_key,
          file_name: file.originalname,
          file_type,
          sort_order: index,
        };
      })
    );

    return ServiceFile.bulkCreate(records);
  }

  async deleteFile(fileId) {
    const file = await ServiceFile.findByPk(fileId);
    if (!file) {
      const err = new Error("File not found.");
      err.statusCode = 404;
      throw err;
    }

    // Delete from S3 Spaces first — if this fails, we do NOT delete the DB record
    // so the file remains tracked and can be retried
    if (file.s3_key) {
      await deleteFileFromS3(file.s3_key);
    }

    await file.destroy();
  }
}

module.exports = ServiceFileService;
